/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "logout": [],
    "invitations.accept": [
        {
            "name": "token",
            "required": true
        }
    ],
    "dashboard": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        }
    ],
    "workspaces": [],
    "tasks.hub": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.index": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.create": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.store": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.edit": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.show": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.update": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.destroy": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.tasks.index": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.tasks.create": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.tasks.store": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        }
    ],
    "projects.tasks.edit": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "task",
            "required": true,
            "binding": "key"
        }
    ],
    "projects.tasks.show": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "task",
            "required": true,
            "binding": "key"
        }
    ],
    "projects.tasks.update": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "task",
            "required": true,
            "binding": "key"
        }
    ],
    "projects.tasks.destroy": [
        {
            "name": "org",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "project",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "task",
            "required": true,
            "binding": "key"
        }
    ]
}
}
export {};
