/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "logout": [],
    "invitations.accept": [
        {
            "name": "token",
            "required": true
        }
    ],
    "dashboard": [],
    "projects.index": [],
    "tasks.hub": [],
    "projects.tasks.index": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.tasks.create": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.tasks.store": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.tasks.edit": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.tasks.show": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.tasks.update": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ],
    "projects.tasks.destroy": [
        {
            "name": "project",
            "required": true,
            "binding": "id"
        },
        {
            "name": "task",
            "required": true,
            "binding": "id"
        }
    ]
}
}
export {};
