/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "invitations.accept": [
        {
            "name": "token",
            "required": true
        }
    ],
    "dashboard": [],
    "projects.index": [],
    "tasks.index": []
}
}
export {};

import type { route as routeFn } from 'ziggy-js';

declare global {
    var route: typeof routeFn;
}
